"""Run Experiment 3 (external numbering) — Koopman / EDMDc observable selection.

Three conditions, single-seed, on the same Quadrotor trajectory dataset:

    B : polynomial-only observable (degree-2 monomials of state, 27 dims)
    P : observable function generated by Qwen 3.6-Plus via DashScope
    Q : observable function generated by Qwen3.5-4B locally via mlx-vlm
        (with explicit equations of motion appendix in the prompt)

All three are fit with EDMDc (ordinary least squares on the lifted
data matrices). Metrics: prediction one-step MSE on validation, and
50-step free-run rollout MSE in lifted space (with re-lifting after
each [:6] state projection). Results written to
``results/koopman_results.csv`` (one row per condition).

LLM artifacts are saved verbatim under
``llm_artifacts/koopman_observables/`` for reproducibility and for
the Final Report's discussion section.

Environment variables:
- ``DASHSCOPE_API_KEY`` — required for the P condition; the script
  silently skips P if not set.
- ``KOOPMAN_SKIP_Q=1`` — set to skip the Q condition (4.8 GB model
  load + minute-scale inference). Useful during iteration on B or P.

Usage::

    DASHSCOPE_API_KEY=sk-... python scripts/run_koopman.py
    KOOPMAN_SKIP_Q=1 DASHSCOPE_API_KEY=sk-... python scripts/run_koopman.py
"""
from __future__ import annotations

import csv
import os
import sys
import time
from pathlib import Path

import numpy as np

from me569_project.data.trajectory_generator import generate_trajectories, TrajectoryData
from me569_project.llm.code_extraction import CodeExtractionError, extract_python_code
from me569_project.llm.prompts import build_koopman_observable_prompt
from me569_project.llm.qwen_local_client import QwenLocalClient, QwenLocalError
from me569_project.llm.qwen_plus_client import QwenPlusClient, QwenPlusError
from me569_project.llm.sandbox import SandboxError, load_callable
from me569_project.sysid.edmdc import (
    EDMDcResult,
    edmdc_one_step_mse,
    edmdc_rollout_mse,
    fit_edmdc,
)
from me569_project.sysid.koopman_baselines import polynomial_observable


REPO_ROOT = Path(__file__).resolve().parent.parent

# ``KOOPMAN_OUTPUT_SUFFIX`` lets a rerun under a different prompt write
# to parallel paths (e.g. ``KOOPMAN_OUTPUT_SUFFIX=_clean`` writes to
# ``results/koopman_results_clean.csv`` and
# ``llm_artifacts/koopman_observables_clean/...``) without overwriting
# the original CSV / artifacts. See the 2026-05-03 prompt audit.
_OUTPUT_SUFFIX = os.environ.get("KOOPMAN_OUTPUT_SUFFIX", "")
RESULTS_CSV = REPO_ROOT / "results" / f"koopman_results{_OUTPUT_SUFFIX}.csv"
ARTIFACTS_DIR = (
    REPO_ROOT / "llm_artifacts" / f"koopman_observables{_OUTPUT_SUFFIX}"
)


def _flatten(data: TrajectoryData) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Flatten TrajectoryData into (X, U, X_next) flat arrays."""
    X = data.states[:, :-1, :].reshape(-1, 6)
    U = data.actions.reshape(-1, 2)
    X_next = data.next_states.reshape(-1, 6)
    return X, U, X_next


def _evaluate(
    result: EDMDcResult,
    val: TrajectoryData,
    rollout_horizon: int = 50,
) -> dict:
    """Compute one-step and rollout MSE on the validation set."""
    X_va, U_va, X_va_next = _flatten(val)
    one_step = edmdc_one_step_mse(result, X_va, U_va, X_va_next)

    X0 = val.states[:, 0, :]
    U_seq = val.actions
    X_seq_true = val.states[:, 1:, :]
    rollout_50 = edmdc_rollout_mse(
        result, X0, U_seq, X_seq_true, horizon=rollout_horizon
    )
    return {
        "one_step_mse": one_step,
        "rollout_mse_50": rollout_50,
    }


def run_baseline_condition(
    train: TrajectoryData,
    val: TrajectoryData,
) -> dict:
    """Fit and evaluate the B (polynomial) condition."""
    X_tr, U_tr, X_tr_next = _flatten(train)
    print("[B] Fitting EDMDc with polynomial observable (degree 2, 27 dims) ...")
    t0 = time.time()
    res = fit_edmdc(
        X_tr, U_tr, X_tr_next, polynomial_observable,
        observable_name="B-polynomial-deg2",
    )
    fit_time = time.time() - t0
    print(f"[B]   fit done in {fit_time:.2f}s, n_obs={res.n_obs}, "
          f"train_one_step_mse={res.train_one_step_mse:.4e}")

    metrics = _evaluate(res, val)
    print(f"[B]   val one_step_mse   = {metrics['one_step_mse']:.4e}")
    print(f"[B]   val rollout_mse_50 = {metrics['rollout_mse_50']:.4e}")

    return {
        "condition": "B",
        "observable_description": "polynomial degree 2 (state + 6 squares + 15 cross terms)",
        "n_obs": res.n_obs,
        "fit_time_s": fit_time,
        "train_one_step_mse": res.train_one_step_mse,
        **metrics,
    }


def _validate_and_load_observable(
    code: str,
    function_name: str = "observables",
) -> tuple[callable, int] | None:
    """Load the LLM-generated function from a code string and probe it.

    Returns (callable, n_obs) on success, or None on failure (with a
    printed error). A successful return means the observable passes
    the sandbox loader, runs on a sentinel input, returns a
    [6, 50]-dim vector, and the first 6 components equal the input.
    """
    try:
        fn = load_callable(code, function_name=function_name)
    except SandboxError as e:
        print(f"      sandbox failed to load function: {e}")
        return None

    sentinel = np.array([0.5, -0.3, 0.1, 0.2, -0.1, 0.05])
    try:
        out = np.asarray(fn(sentinel), dtype=np.float64).ravel()
    except Exception as e:
        print(f"      observable crashed on sentinel: {e}")
        return None

    if not np.all(np.isfinite(out)):
        print("      observable produced non-finite output on sentinel")
        return None
    n_obs = out.shape[0]
    if n_obs < 6 or n_obs > 50:
        print(f"      observable dim {n_obs} out of allowed range [6, 50]")
        return None
    if not np.allclose(out[:6], sentinel, atol=1e-10):
        print(
            f"      observable violates state-recovery convention "
            f"(first 6 != input). Got {out[:6]}, expected {sentinel}"
        )
        return None

    return fn, n_obs


def _save_artifact(code: str, run_label: str) -> Path:
    ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)
    path = ARTIFACTS_DIR / f"{run_label}.py"
    path.write_text(code)
    print(f"      saved observable code to {path}")
    return path


def run_qwen_plus_condition(
    train: TrajectoryData,
    val: TrajectoryData,
) -> dict | None:
    """Call Qwen 3.6-Plus, validate the observable, fit EDMDc, evaluate."""
    api_key = os.environ.get("DASHSCOPE_API_KEY")
    if not api_key:
        print("[P] DASHSCOPE_API_KEY not set, skipping P condition.")
        return None

    client = QwenPlusClient(api_key=api_key, max_tokens=4096)
    prompt = build_koopman_observable_prompt(include_eom=False)
    print(f"[P] Calling Qwen 3.6-Plus (prompt length: {len(prompt)} chars) ...")
    t0 = time.time()
    try:
        response = client.call(prompt)
    except QwenPlusError as e:
        print(f"[P] Qwen 3.6-Plus call failed: {e}")
        return None
    call_time = time.time() - t0
    tokens = (
        client.last_usage.get("total_tokens", "?") if client.last_usage else "?"
    )
    print(f"[P]   response received in {call_time:.1f}s, tokens={tokens}")

    try:
        code = extract_python_code(response)
    except CodeExtractionError as e:
        print(f"[P] Failed to extract code from response: {e}")
        print(response[:1500])
        return None

    print(f"[P]   extracted code ({len(code)} chars):")
    print("-" * 60)
    print(code)
    print("-" * 60)

    loaded = _validate_and_load_observable(code)
    if loaded is None:
        return None
    obs_fn, _ = loaded

    print("[P] Fitting EDMDc with Qwen 3.6-Plus observable ...")
    t1 = time.time()
    res = fit_edmdc(
        *_flatten(train), obs_fn, observable_name="P-Qwen-Plus-run-01"
    )
    fit_time = time.time() - t1
    print(f"[P]   fit done in {fit_time:.2f}s, n_obs={res.n_obs}, "
          f"train_one_step_mse={res.train_one_step_mse:.4e}")

    _save_artifact(code, "p_qwen_plus_run_01")

    metrics = _evaluate(res, val)
    print(f"[P]   val one_step_mse   = {metrics['one_step_mse']:.4e}")
    print(f"[P]   val rollout_mse_50 = {metrics['rollout_mse_50']:.4e}")

    return {
        "condition": "P",
        "observable_description": "Qwen 3.6-Plus generated",
        "n_obs": res.n_obs,
        "fit_time_s": fit_time,
        "train_one_step_mse": res.train_one_step_mse,
        "llm_call_time_s": call_time,
        "llm_model": "qwen-plus",
        "llm_total_tokens": (
            client.last_usage.get("total_tokens", 0) if client.last_usage else 0
        ),
        "llm_request_id": client.last_request_id or "",
        **metrics,
    }


def run_qwen_local_condition(
    train: TrajectoryData,
    val: TrajectoryData,
) -> dict | None:
    """Call Qwen3.5-4B locally with EOM appendix and `/no_think`,
    validate the observable, fit EDMDc, evaluate.
    """
    # max_tokens 16384 mirrors the E2 setting: Q's `/no_think`
    # response can be long when it dumps multiple def blocks.
    #
    # The ``/no_think`` directive is prepended to the user-side
    # prompt — same convention as the MPC cost runner. Without it, Q
    # enters its `<think>` reasoning mode by default and on the audited
    # clean prompt rambled in repeated paragraphs until hitting
    # max_tokens, never reaching a code fence.
    client = QwenLocalClient(max_tokens=4096)
    base_prompt = build_koopman_observable_prompt(include_eom=True)
    prompt = f"/no_think\n\n{base_prompt}"
    print(f"[Q] Calling Qwen3.5-4B with /no_think + EOM appendix "
          f"(prompt length: {len(prompt)} chars) ...")
    print("[Q]   (first call loads 4.8 GB model; subsequent calls reuse cache)")
    t0 = time.time()
    try:
        response = client.call(prompt)
    except QwenLocalError as e:
        print(f"[Q] Qwen3.5-4B call failed: {e}")
        return None
    call_time = time.time() - t0
    load_time = client.last_load_time_s or 0.0
    gen_time = client.last_call_time_s or 0.0
    print(f"[Q]   response received in {call_time:.1f}s "
          f"(load {load_time:.1f}s, generate {gen_time:.1f}s)")

    try:
        code = extract_python_code(response)
    except CodeExtractionError as e:
        print(f"[Q] Failed to extract code from response: {e}")
        print(response[:1500])
        return None

    print(f"[Q]   extracted code ({len(code)} chars):")
    print("-" * 60)
    print(code)
    print("-" * 60)

    loaded = _validate_and_load_observable(code)
    if loaded is None:
        return None
    obs_fn, _ = loaded

    print("[Q] Fitting EDMDc with Qwen3.5-4B observable ...")
    t1 = time.time()
    res = fit_edmdc(
        *_flatten(train), obs_fn, observable_name="Q-Qwen3.5-4B-run-01"
    )
    fit_time = time.time() - t1
    print(f"[Q]   fit done in {fit_time:.2f}s, n_obs={res.n_obs}, "
          f"train_one_step_mse={res.train_one_step_mse:.4e}")

    _save_artifact(code, "q_qwen_local_run_01")

    metrics = _evaluate(res, val)
    print(f"[Q]   val one_step_mse   = {metrics['one_step_mse']:.4e}")
    print(f"[Q]   val rollout_mse_50 = {metrics['rollout_mse_50']:.4e}")

    return {
        "condition": "Q",
        "observable_description": "Qwen3.5-4B generated (with EOM appendix)",
        "n_obs": res.n_obs,
        "fit_time_s": fit_time,
        "train_one_step_mse": res.train_one_step_mse,
        "llm_call_time_s": call_time,
        "llm_load_time_s": load_time,
        "llm_generate_time_s": gen_time,
        "llm_model": "Qwen3.5-4B-MLX-8bit",
        **metrics,
    }


def write_results_csv(rows: list[dict], path: Path) -> None:
    if not rows:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    keys: list[str] = []
    seen = set()
    for row in rows:
        for k in row.keys():
            if k not in seen:
                keys.append(k)
                seen.add(k)
    with path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=keys)
        writer.writeheader()
        for row in rows:
            writer.writerow({k: row.get(k, "") for k in keys})
    print(f"\nWrote {len(rows)} row(s) to {path}")


def main() -> None:
    num_train = 500
    num_val = 100
    steps_per_traj = 400

    print(f"Generating {num_train} train + {num_val} val trajectories at "
          f"{steps_per_traj} steps each ...")
    t0 = time.time()
    train = generate_trajectories(
        num_trajectories=num_train,
        steps_per_trajectory=steps_per_traj,
        seed=0,
    )
    val = generate_trajectories(
        num_trajectories=num_val,
        steps_per_trajectory=steps_per_traj,
        seed=42,
    )
    print(f"Data done in {time.time() - t0:.1f}s "
          f"({train.num_transitions} train transitions, "
          f"{val.num_transitions} val transitions)")

    results: list[dict] = []

    # Baseline (B)
    print()
    results.append(run_baseline_condition(train, val))

    # Qwen 3.6-Plus (P)
    print()
    p_row = run_qwen_plus_condition(train, val)
    if p_row is not None:
        results.append(p_row)

    # Qwen3.5-4B (Q)
    if os.environ.get("KOOPMAN_SKIP_Q"):
        print()
        print("[Q] KOOPMAN_SKIP_Q is set, skipping Q condition.")
    else:
        print()
        q_row = run_qwen_local_condition(train, val)
        if q_row is not None:
            results.append(q_row)

    print()
    print("=" * 76)
    print("E3 (Koopman/EDMDc) Results Summary")
    print("=" * 76)
    print(f"{'cond':4s} {'n_obs':>6s} {'fit_s':>8s} "
          f"{'train_1step':>14s} {'val_1step':>14s} {'roll_50':>14s}")
    for r in results:
        print(
            f"{r['condition']:4s} {r['n_obs']:6d} {r['fit_time_s']:8.2f} "
            f"{r['train_one_step_mse']:14.4e} {r['one_step_mse']:14.4e} "
            f"{r['rollout_mse_50']:14.4e}"
        )
    print("=" * 76)

    write_results_csv(results, RESULTS_CSV)


if __name__ == "__main__":
    sys.exit(main())
