"""Run Experiment 3 (MPC stage cost design) for B, P, and Q conditions.

Mirrors ``scripts/run_e1_full.py`` but for the MPC stage cost task:

    B : hand-written quadratic xᵀQx + (u-u_hover)ᵀR(u-u_hover)
    P : stage cost generated by Qwen-Plus via the DashScope API
    Q : stage cost generated by Qwen3.5-4B via mlx-vlm locally

All three conditions feed the SAME closed-loop evaluation harness on
the SAME random initial states. The only variable is which stage cost
plugs into ``PlanarQuadrotorMPC``. The MPC predictor uses
the **ground-truth** quadrotor dynamics — there is no SINDy in the
loop, so any performance difference is purely due to the cost
function design.

Metrics (per Section 3.4):
- ``hover_success_rate`` (fraction in [0, 1])
- ``mean_settling_time_s`` (seconds; NaN if no rollouts converged)
- ``mean_control_energy`` (∫‖u - u_hover‖² dt averaged over rollouts)

Plus the LLM accounting from E1: tokens, latency, model identifier.

Environment:
- ``DASHSCOPE_API_KEY``: required for P; the script skips P if unset.
- ``E3_SKIP_Q=1``: skip Qwen3.5-4B (saves ~5 minutes of edge inference).

Usage::

    DASHSCOPE_API_KEY=sk-... python scripts/run_e3_full.py
"""
from __future__ import annotations

import csv
import os
import sys
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Callable

from me569_project.llm.code_extraction import (
    CodeExtractionError,
    extract_python_code,
)
from me569_project.llm.prompts import build_mpc_cost_prompt
from me569_project.llm.qwen_local_client import QwenLocalClient, QwenLocalError
from me569_project.llm.qwen_plus_client import QwenPlusClient, QwenPlusError
from me569_project.llm.sandbox import SandboxError
from me569_project.mpc.baseline_cost import make_baseline_stage_cost
from me569_project.mpc.evaluation import evaluate_controller
from me569_project.mpc.mpc_math import load_stage_cost_callable
from me569_project.mpc.mpc_wrapper import MPCConfig, PlanarQuadrotorMPC
from me569_project.quadrotor_dynamics import QuadrotorParams


REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_SUFFIX = os.environ.get("E3_OUTPUT_SUFFIX", "")
BASES_DIR = REPO_ROOT / "llm_artifacts" / f"e3_costs{OUTPUT_SUFFIX}"
BASES_DIR.mkdir(parents=True, exist_ok=True)
RESULTS_CSV = REPO_ROOT / "results" / f"e3_results{OUTPUT_SUFFIX}.csv"


@dataclass
class E3Row:
    condition: str
    n_initial_states: int
    horizon: int
    hover_success_rate: float
    num_successful: int
    mean_settling_time_s: float
    median_settling_time_s: float
    mean_control_energy: float
    mean_final_position_error: float
    mean_final_attitude_error: float
    failed_due_to_crash: int
    failed_due_to_timeout: int
    fit_or_call_time_s: float
    llm_model: str
    llm_total_tokens: int
    cost_file: str


def _save_cost_code(stem: str, header: str, code: str) -> Path:
    path = BASES_DIR / f"{stem}.py"
    wrapped = f'"""{header}\n"""\n{code}\n'
    path.write_text(wrapped)
    return path


def _build_mpc(
    stage_cost: Callable, params: QuadrotorParams, horizon: int
) -> PlanarQuadrotorMPC:
    return PlanarQuadrotorMPC(
        params=params,
        stage_cost=stage_cost,
        config=MPCConfig(horizon=horizon),
    )


def _evaluate(
    label: str,
    stage_cost: Callable,
    params: QuadrotorParams,
    num_initial_states: int,
    horizon: int,
    seed: int,
) -> dict:
    print(f"  [{label}] Building MPC controller (horizon={horizon}) ...")
    t0 = time.time()
    mpc = _build_mpc(stage_cost, params, horizon)
    build_time = time.time() - t0
    print(f"  [{label}]   built in {build_time:.1f}s")

    print(f"  [{label}] Running {num_initial_states} closed-loop rollouts ...")
    t0 = time.time()
    result = evaluate_controller(
        mpc,
        params=params,
        num_initial_states=num_initial_states,
        seed=seed,
    )
    eval_time = time.time() - t0
    print(
        f"  [{label}]   eval done in {eval_time:.1f}s "
        f"(success={result.hover_success_rate:.2%}, "
        f"settle={result.mean_settling_time_s:.2f}s, "
        f"energy={result.mean_control_energy:.3f})"
    )
    return {"build_time": build_time, "eval_time": eval_time, "result": result}


def run_baseline(
    params: QuadrotorParams,
    num_initial_states: int,
    horizon: int,
    seed: int,
) -> E3Row:
    print()
    print("[B] Hand-written quadratic baseline (default Q, R)")
    cost_fn = make_baseline_stage_cost(params=params)
    out = _evaluate("B", cost_fn, params, num_initial_states, horizon, seed)
    r = out["result"]
    return E3Row(
        condition="B",
        n_initial_states=num_initial_states,
        horizon=horizon,
        hover_success_rate=r.hover_success_rate,
        num_successful=r.num_successful,
        mean_settling_time_s=r.mean_settling_time_s,
        median_settling_time_s=r.median_settling_time_s,
        mean_control_energy=r.mean_control_energy,
        mean_final_position_error=r.mean_final_position_error,
        mean_final_attitude_error=r.mean_final_attitude_error,
        failed_due_to_crash=r.failed_due_to_crash,
        failed_due_to_timeout=r.failed_due_to_timeout,
        fit_or_call_time_s=out["build_time"] + out["eval_time"],
        llm_model="-",
        llm_total_tokens=0,
        cost_file="(in-repo make_baseline_stage_cost)",
    )


def run_qwen_plus(
    params: QuadrotorParams,
    num_initial_states: int,
    horizon: int,
    seed: int,
) -> E3Row | None:
    api_key = os.environ.get("DASHSCOPE_API_KEY")
    if not api_key:
        print("[P] DASHSCOPE_API_KEY not set, skipping P condition.")
        return None

    print()
    print("[P] Qwen-Plus stage cost (Qwen 3.6 backend)")
    client = QwenPlusClient(api_key=api_key, max_tokens=1500)
    prompt = build_mpc_cost_prompt()
    print(f"  prompt length: {len(prompt)} chars")
    t0 = time.time()
    try:
        response = client.call(prompt)
    except QwenPlusError as e:
        print(f"  Qwen-Plus call failed: {e}")
        return None
    call_time = time.time() - t0
    tokens = (
        client.last_usage.get("total_tokens", 0) if client.last_usage else 0
    )
    print(f"  response received in {call_time:.1f}s ({tokens} tokens)")

    try:
        code = extract_python_code(response)
    except CodeExtractionError as e:
        print(f"  extract failed: {e}")
        return None

    stem = "p_qwen_plus_run_01"
    path = _save_cost_code(
        stem,
        header=(
            "P-condition stage cost from Qwen-Plus run 01 (Qwen 3.6). "
            "Saved by scripts/run_e3_full.py."
        ),
        code=code,
    )
    print(f"  saved {path.name} ({len(code)} chars)")

    try:
        cost_fn = load_stage_cost_callable(code, function_name="stage_cost")
    except SandboxError as e:
        print(f"  Sandbox load failed: {e}")
        return None

    try:
        out = _evaluate("P", cost_fn, params, num_initial_states, horizon, seed)
    except Exception as e:
        print(f"  MPC build/eval failed: {type(e).__name__}: {e}")
        return None

    r = out["result"]
    return E3Row(
        condition="P",
        n_initial_states=num_initial_states,
        horizon=horizon,
        hover_success_rate=r.hover_success_rate,
        num_successful=r.num_successful,
        mean_settling_time_s=r.mean_settling_time_s,
        median_settling_time_s=r.median_settling_time_s,
        mean_control_energy=r.mean_control_energy,
        mean_final_position_error=r.mean_final_position_error,
        mean_final_attitude_error=r.mean_final_attitude_error,
        failed_due_to_crash=r.failed_due_to_crash,
        failed_due_to_timeout=r.failed_due_to_timeout,
        fit_or_call_time_s=call_time,
        llm_model="qwen-plus (Qwen 3.6)",
        llm_total_tokens=tokens,
        cost_file=path.name,
    )


def run_qwen_local(
    params: QuadrotorParams,
    num_initial_states: int,
    horizon: int,
    seed: int,
) -> E3Row | None:
    if os.environ.get("E3_SKIP_Q"):
        print("[Q] E3_SKIP_Q is set, skipping Qwen3.5-4B condition.")
        return None

    print()
    print("[Q] Qwen3.5-4B stage cost (mlx-vlm local)")
    # E3 prompt is denser than E1 (10 constraint rules) and Qwen3.5-4B's
    # thinking mode enters a degenerate verification loop on it,
    # repeating "Wait, I need to ensure I don't use np.X" indefinitely
    # regardless of the max_tokens budget (observed at both 2000 and
    # 4000 tokens; see commit 8251801 message for the forensic trace).
    #
    # The fix probed in scripts/probe_q_e3_strategies.py: prepending
    # the Qwen3 ``/no_think`` directive disables thinking mode and the
    # model emits a clean stage_cost function. Same underlying prompt
    # as the P condition, so the B/P/Q comparison is still fair — only
    # the thinking-mode toggle differs, which is itself a measurable
    # edge-vs-frontier behavior difference worth reporting.
    client = QwenLocalClient(max_tokens=4000)
    base_prompt = build_mpc_cost_prompt()
    prompt = f"/no_think\n\n{base_prompt}"
    print(f"  prompt length: {len(prompt)} chars (/no_think + E3 prompt)")
    print("  (first call loads 4.8 GB model; subsequent calls use cache)")
    t0 = time.time()
    try:
        response = client.call(prompt)
    except QwenLocalError as e:
        print(f"  Qwen3.5-4B call failed: {e}")
        return None
    call_time = time.time() - t0
    print(f"  response received in {call_time:.1f}s")

    try:
        code = extract_python_code(response)
    except CodeExtractionError as e:
        print(f"  extract failed: {e}")
        return None

    stem = "q_qwen_local_run_01"
    path = _save_cost_code(
        stem,
        header=(
            "Q-condition stage cost from Qwen3.5-4B-MLX-8bit run 01. "
            "Saved by scripts/run_e3_full.py."
        ),
        code=code,
    )
    print(f"  saved {path.name} ({len(code)} chars)")

    try:
        cost_fn = load_stage_cost_callable(code, function_name="stage_cost")
    except SandboxError as e:
        print(f"  Sandbox load failed: {e}")
        return None

    try:
        out = _evaluate("Q", cost_fn, params, num_initial_states, horizon, seed)
    except Exception as e:
        print(f"  MPC build/eval failed: {type(e).__name__}: {e}")
        return None

    r = out["result"]
    return E3Row(
        condition="Q",
        n_initial_states=num_initial_states,
        horizon=horizon,
        hover_success_rate=r.hover_success_rate,
        num_successful=r.num_successful,
        mean_settling_time_s=r.mean_settling_time_s,
        median_settling_time_s=r.median_settling_time_s,
        mean_control_energy=r.mean_control_energy,
        mean_final_position_error=r.mean_final_position_error,
        mean_final_attitude_error=r.mean_final_attitude_error,
        failed_due_to_crash=r.failed_due_to_crash,
        failed_due_to_timeout=r.failed_due_to_timeout,
        fit_or_call_time_s=call_time,
        llm_model="Qwen3.5-4B-MLX-8bit",
        llm_total_tokens=0,
        cost_file=path.name,
    )


def write_results_csv(rows: list[E3Row], path: Path) -> None:
    if not rows:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(asdict(rows[0]).keys()))
        writer.writeheader()
        for r in rows:
            writer.writerow(asdict(r))
    print(f"\nWrote {len(rows)} rows to {path}")


def main() -> int:
    params = QuadrotorParams()
    num_initial_states = 20
    horizon = 20
    seed = 0

    print("=" * 90)
    print(f"Experiment 3 — MPC stage cost (B + P + Q)")
    print(f"  num_initial_states = {num_initial_states}")
    print(f"  horizon            = {horizon}")
    print(f"  init_seed          = {seed}")
    print("=" * 90)

    rows: list[E3Row] = []

    rows.append(run_baseline(params, num_initial_states, horizon, seed))

    p_row = run_qwen_plus(params, num_initial_states, horizon, seed)
    if p_row is not None:
        rows.append(p_row)

    q_row = run_qwen_local(params, num_initial_states, horizon, seed)
    if q_row is not None:
        rows.append(q_row)

    print()
    print("=" * 90)
    print("E3 Results Summary")
    print("=" * 90)
    print(
        f"{'cond':<5s} {'success':>10s} {'settle_s':>10s} {'energy':>10s} "
        f"{'final_pos':>10s} {'crash':>6s} {'timeout':>8s}"
    )
    for r in rows:
        settle_str = (
            f"{r.mean_settling_time_s:.2f}"
            if r.mean_settling_time_s == r.mean_settling_time_s
            else "  nan"
        )
        print(
            f"{r.condition:<5s} {r.hover_success_rate:>10.2%} "
            f"{settle_str:>10s} {r.mean_control_energy:>10.3f} "
            f"{r.mean_final_position_error:>10.4f} "
            f"{r.failed_due_to_crash:>6d} {r.failed_due_to_timeout:>8d}"
        )
    print("=" * 90)

    write_results_csv(rows, RESULTS_CSV)
    return 0


if __name__ == "__main__":
    sys.exit(main())
