"""Run Experiment 4 (external numbering) — Eureka-style RL reward design.

Three conditions, three PPO seeds each, on the Planar Quadrotor hover task:

    B : textbook negative-quadratic baseline reward (Bryson's-rule weights).
    P : reward function generated by Qwen 3.6-Plus (DashScope), zero-shot.
    Q : reward function generated by Qwen3.5-4B locally via mlx-vlm, with
        the explicit equations of motion appendix and ``/no_think`` directive.

Each (condition, seed) is trained with stable-baselines3 PPO for
``total_timesteps`` steps and evaluated on a fixed set of 20 initial
states (E2-comparable). Per-seed metrics: hover_success_rate, settling
time, control energy, final position / attitude error, crash / timeout
counts. Aggregated mean ± std reported across the 3 seeds.

Training uses ``init_radius=0.15`` (where PPO converges reliably in
~300k steps on M4 CPU). Evaluation runs at TWO radii — 0.15 for the
train distribution and 0.30 for the E2-comparable distribution —
to measure generalization.

Outputs:
- ``results/eureka_results.csv`` — per-seed rows, both eval radii.
- ``results/eureka_training_curves.npz`` — learning curves per (cond, seed).
- ``llm_artifacts/eureka_rewards/{p,q}_*_run_01.py`` — saved LLM reward code.

Env vars:
- ``DASHSCOPE_API_KEY`` required for P. Skipped silently if unset.
- ``EUREKA_SKIP_Q=1`` skips the Q condition (saves model load + 3 PPO trainings).
- ``EUREKA_QUICK=1`` reduces total_timesteps to 50k for smoke testing.
- ``EUREKA_OUTPUT_SUFFIX=_clean`` parallel output paths (mirrors E3 audit pattern).
"""
from __future__ import annotations

import csv
import os
import sys
import time
from pathlib import Path

import numpy as np

from me569_project.llm.code_extraction import (
    CodeExtractionError,
    extract_python_code,
)
from me569_project.llm.prompts import build_eureka_reward_prompt
from me569_project.llm.qwen_local_client import QwenLocalClient, QwenLocalError
from me569_project.llm.qwen_plus_client import QwenPlusClient, QwenPlusError
from me569_project.llm.sandbox import SandboxError, load_callable
from me569_project.rl.eureka_rewards import baseline_reward, clip_reward
from me569_project.rl.ppo_runner import EvalResult, evaluate_ppo, train_ppo


REPO_ROOT = Path(__file__).resolve().parent.parent
_SUFFIX = os.environ.get("EUREKA_OUTPUT_SUFFIX", "")
RESULTS_CSV = REPO_ROOT / "results" / f"eureka_results{_SUFFIX}.csv"
CURVES_NPZ = REPO_ROOT / "results" / f"eureka_training_curves{_SUFFIX}.npz"
ARTIFACTS_DIR = REPO_ROOT / "llm_artifacts" / f"eureka_rewards{_SUFFIX}"

PPO_SEEDS = [0, 1, 2]
TRAIN_INIT_RADIUS = 0.15
EVAL_RADII = [0.15, 0.30]  # train-distribution and E2-matched
QUICK_TIMESTEPS = 50_000
FULL_TIMESTEPS = 300_000


def _validate_reward_function(fn) -> bool:
    """Run sentinel checks on an LLM-generated reward.

    Returns True if the function passes basic sanity (finite output,
    higher at hover than at a disturbed state, non-trivial variance).
    """
    sentinels_state = [
        np.zeros(6),
        np.array([0.5, -0.3, 0.1, 0.2, -0.1, 0.05]),
        np.array([1.0, 1.0, 0.5, -0.5, 0.5, -0.5]),
    ]
    sentinels_action = [
        np.array([4.905, 4.905]),
        np.array([4.905, 4.905]),
        np.array([4.905, 4.905]),
    ]
    rewards = []
    for s, a in zip(sentinels_state, sentinels_action):
        try:
            r = float(fn(s, a))
        except Exception as e:
            print(f"      reward function crashed on sentinel: {e}")
            return False
        if not np.isfinite(r):
            print(f"      reward returned non-finite value: {r!r}")
            return False
        rewards.append(r)

    if not (rewards[0] > rewards[1] and rewards[0] > rewards[2]):
        print(
            f"      reward at hover ({rewards[0]:.3f}) is not strictly "
            f"greater than at disturbed states ({rewards[1]:.3f}, "
            f"{rewards[2]:.3f}). Reject."
        )
        return False
    return True


def _save_reward_artifact(code: str, label: str) -> Path:
    ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)
    path = ARTIFACTS_DIR / f"{label}.py"
    path.write_text(code)
    print(f"      saved reward code to {path}")
    return path


def _eval_to_dict(metrics: EvalResult, init_radius: float) -> dict:
    return {
        f"hover_success_rate@{init_radius}": metrics.hover_success_rate,
        f"mean_settling_time_s@{init_radius}": metrics.mean_settling_time_s,
        f"mean_control_energy@{init_radius}": metrics.mean_control_energy,
        f"mean_final_position_error@{init_radius}": metrics.mean_final_position_error,
        f"mean_final_attitude_error@{init_radius}": metrics.mean_final_attitude_error,
        f"failed_due_to_crash@{init_radius}": metrics.failed_due_to_crash,
        f"failed_due_to_timeout@{init_radius}": metrics.failed_due_to_timeout,
    }


def run_condition_seeds(
    condition: str,
    reward_fn,
    total_timesteps: int,
    description: str,
    extra: dict | None = None,
) -> tuple[list[dict], dict]:
    """Train ``len(PPO_SEEDS)`` PPO models with the same reward and return rows.

    Also returns a dict ``{seed: (steps, rewards)}`` of learning curves.
    """
    rows: list[dict] = []
    curves: dict[int, tuple[np.ndarray, np.ndarray]] = {}
    for seed in PPO_SEEDS:
        print(f"  [{condition}|seed={seed}] training {total_timesteps:,} steps ...")
        t0 = time.time()
        train = train_ppo(
            reward_fn=reward_fn,
            total_timesteps=total_timesteps,
            seed=seed,
            n_envs=8,
            init_radius=TRAIN_INIT_RADIUS,
            device="cpu",
        )
        train_time = time.time() - t0
        curves[seed] = (
            train.learning_curve_steps.copy(),
            train.learning_curve_rewards.copy(),
        )
        last_curve_reward = (
            float(train.learning_curve_rewards[-1])
            if len(train.learning_curve_rewards)
            else float("nan")
        )
        print(
            f"  [{condition}|seed={seed}]   trained in {train_time:.1f}s, "
            f"final_ep_rew_mean={last_curve_reward:.1f}"
        )

        row: dict = {
            "condition": condition,
            "seed": seed,
            "total_timesteps": total_timesteps,
            "train_time_s": train_time,
            "final_ep_rew_mean": last_curve_reward,
            "reward_description": description,
        }

        for init_radius in EVAL_RADII:
            metrics = evaluate_ppo(
                train.model,
                num_initial_states=20,
                init_radius=init_radius,
                seed=0,  # fixed eval seed for apples-to-apples
            )
            row.update(_eval_to_dict(metrics, init_radius))
            print(
                f"  [{condition}|seed={seed}]   eval@{init_radius}: "
                f"success={metrics.hover_success_rate:.2f}, "
                f"settle={metrics.mean_settling_time_s:.2f}, "
                f"energy={metrics.mean_control_energy:.4f}"
            )

        if extra:
            row.update(extra)
        rows.append(row)

    return rows, curves


def run_qwen_plus_reward(total_timesteps: int) -> tuple[list[dict] | None, dict | None]:
    api_key = os.environ.get("DASHSCOPE_API_KEY")
    if not api_key:
        print("[P] DASHSCOPE_API_KEY not set, skipping P condition.")
        return None, None

    client = QwenPlusClient(api_key=api_key, max_tokens=4096)
    prompt = build_eureka_reward_prompt(include_eom=False)
    print(f"[P] Calling Qwen 3.6-Plus (prompt length: {len(prompt)} chars) ...")
    t0 = time.time()
    try:
        response = client.call(prompt)
    except QwenPlusError as e:
        print(f"[P] Qwen 3.6-Plus call failed: {e}")
        return None, None
    call_time = time.time() - t0
    tokens = (
        client.last_usage.get("total_tokens", "?") if client.last_usage else "?"
    )
    print(f"[P]   response received in {call_time:.1f}s, tokens={tokens}")

    try:
        code = extract_python_code(response)
    except CodeExtractionError as e:
        print(f"[P] Failed to extract code: {e}")
        return None, None

    print(f"[P]   extracted code ({len(code)} chars)")
    print("-" * 60)
    print(code)
    print("-" * 60)

    try:
        raw_fn = load_callable(code, function_name="reward")
    except SandboxError as e:
        print(f"[P] Sandbox failed to load reward function: {e}")
        return None, None

    if not _validate_reward_function(raw_fn):
        return None, None

    fn = clip_reward(raw_fn, low=-1000.0, high=1000.0)
    _save_reward_artifact(code, "p_qwen_plus_run_01")

    extra = {
        "llm_call_time_s": call_time,
        "llm_model": "qwen-plus",
        "llm_total_tokens": (
            client.last_usage.get("total_tokens", 0)
            if client.last_usage else 0
        ),
        "llm_request_id": client.last_request_id or "",
    }
    return run_condition_seeds("P", fn, total_timesteps, "Qwen 3.6-Plus generated", extra)


def run_qwen_local_reward(total_timesteps: int) -> tuple[list[dict] | None, dict | None]:
    client = QwenLocalClient(max_tokens=4096)
    base_prompt = build_eureka_reward_prompt(include_eom=True)
    prompt = f"/no_think\n\n{base_prompt}"
    print(
        f"[Q] Calling Qwen3.5-4B with /no_think + EOM appendix "
        f"(prompt length: {len(prompt)} chars) ..."
    )
    print("[Q]   (first call loads 4.8 GB model; subsequent calls reuse cache)")
    t0 = time.time()
    try:
        response = client.call(prompt)
    except QwenLocalError as e:
        print(f"[Q] Qwen3.5-4B call failed: {e}")
        return None, None
    call_time = time.time() - t0
    print(f"[Q]   response received in {call_time:.1f}s")

    try:
        code = extract_python_code(response)
    except CodeExtractionError as e:
        print(f"[Q] Failed to extract code: {e}")
        return None, None

    print(f"[Q]   extracted code ({len(code)} chars)")
    print("-" * 60)
    print(code)
    print("-" * 60)

    try:
        raw_fn = load_callable(code, function_name="reward")
    except SandboxError as e:
        print(f"[Q] Sandbox failed to load reward function: {e}")
        return None, None

    if not _validate_reward_function(raw_fn):
        return None, None

    fn = clip_reward(raw_fn, low=-1000.0, high=1000.0)
    _save_reward_artifact(code, "q_qwen_local_run_01")

    extra = {
        "llm_call_time_s": call_time,
        "llm_model": "Qwen3.5-4B-MLX-8bit",
    }
    return run_condition_seeds("Q", fn, total_timesteps, "Qwen3.5-4B generated (with EOM)", extra)


def write_csv(rows: list[dict], path: Path) -> None:
    if not rows:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    keys: list[str] = []
    seen = set()
    for row in rows:
        for k in row:
            if k not in seen:
                keys.append(k)
                seen.add(k)
    with path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=keys)
        writer.writeheader()
        for row in rows:
            writer.writerow({k: row.get(k, "") for k in keys})
    print(f"\nWrote {len(rows)} row(s) to {path}")


def main() -> None:
    quick = bool(os.environ.get("EUREKA_QUICK"))
    total_timesteps = QUICK_TIMESTEPS if quick else FULL_TIMESTEPS

    print("=" * 76)
    print(
        f"Experiment 4 (Eureka RL): hover task, {total_timesteps:,} steps, "
        f"{len(PPO_SEEDS)} seeds per condition"
    )
    print("=" * 76)

    all_rows: list[dict] = []
    all_curves: dict[str, dict] = {}

    print("\n[B] baseline (textbook negative-quadratic) reward")
    b_rows, b_curves = run_condition_seeds(
        "B", baseline_reward, total_timesteps,
        description="textbook negative-quadratic (Bryson)",
    )
    all_rows.extend(b_rows)
    all_curves["B"] = b_curves

    print("\n[P] Qwen 3.6-Plus reward")
    p_rows, p_curves = run_qwen_plus_reward(total_timesteps)
    if p_rows is not None:
        all_rows.extend(p_rows)
        all_curves["P"] = p_curves

    if os.environ.get("EUREKA_SKIP_Q"):
        print("\n[Q] EUREKA_SKIP_Q is set, skipping Q condition.")
    else:
        print("\n[Q] Qwen3.5-4B reward")
        q_rows, q_curves = run_qwen_local_reward(total_timesteps)
        if q_rows is not None:
            all_rows.extend(q_rows)
            all_curves["Q"] = q_curves

    print()
    print("=" * 76)
    print("E4 Summary (mean over seeds, eval@0.30)")
    print("=" * 76)
    print(f"{'cond':4s} {'success':>8s} {'settle':>8s} {'energy':>8s} {'crashes':>8s}")
    by_cond: dict[str, list[dict]] = {}
    for r in all_rows:
        by_cond.setdefault(r["condition"], []).append(r)
    for cond in ["B", "P", "Q"]:
        rows = by_cond.get(cond, [])
        if not rows:
            continue
        succ = np.mean([r["hover_success_rate@0.3"] for r in rows])
        settle_vals = [r["mean_settling_time_s@0.3"] for r in rows
                       if not np.isnan(r["mean_settling_time_s@0.3"])]
        settle = np.mean(settle_vals) if settle_vals else float("nan")
        energy = np.mean([r["mean_control_energy@0.3"] for r in rows])
        crashes = sum(int(r["failed_due_to_crash@0.3"]) for r in rows)
        print(
            f"{cond:4s} {succ:8.2f} {settle:8.2f} {energy:8.4f} {crashes:8d}"
        )
    print("=" * 76)

    write_csv(all_rows, RESULTS_CSV)

    if all_curves:
        flat: dict[str, np.ndarray] = {}
        for cond, seed_dict in all_curves.items():
            for seed, (steps, rewards) in seed_dict.items():
                flat[f"{cond}_seed{seed}_steps"] = steps
                flat[f"{cond}_seed{seed}_rewards"] = rewards
        CURVES_NPZ.parent.mkdir(parents=True, exist_ok=True)
        np.savez_compressed(CURVES_NPZ, **flat)
        print(f"Wrote training curves to {CURVES_NPZ}")


if __name__ == "__main__":
    sys.exit(main())
