"""Run Experiment 1 (SINDy basis selection) for B, P, and Q conditions
using the unified LLMBasisSysIDModel pipeline.

All three conditions are fit with pysindy.STLSQ (threshold=0.1) on the
same (Phi, Y) problem, so the only variable is the basis function:

    B : polynomial library of total degree 3 (165 features, textbook
        default by design)
    P : basis function generated by Qwen-Plus via the DashScope API
        (Alibaba frontier cloud, backed by Qwen 3.6)
    Q : basis function generated by Qwen3.5-4B via mlx-vlm locally
        on Apple Silicon

All conditions are evaluated with one_step_mse, rollout_mse at horizon
10 and 50, and active_terms (sparsity). Results are written to
``results/e1_results.csv`` (one row per condition present).

Environment variables:
- ``DASHSCOPE_API_KEY``: required for the P condition; the script skips
  P if not set.
- ``E1_SKIP_Q=1``: set to skip the Q condition (which loads a 4.8 GB
  model and takes ~minute per call on M4 Air). Useful during
  iteration on B or P.

Usage::

    DASHSCOPE_API_KEY=sk-... python scripts/run_e1_full.py
    E1_SKIP_Q=1 DASHSCOPE_API_KEY=sk-... python scripts/run_e1_full.py
"""
from __future__ import annotations

import csv
import os
import sys
import time
from pathlib import Path

from me569_project.data.trajectory_generator import generate_trajectories
from me569_project.llm.code_extraction import CodeExtractionError, extract_python_code
from me569_project.llm.prompts import build_sindy_basis_prompt
from me569_project.llm.qwen_local_client import QwenLocalClient, QwenLocalError
from me569_project.llm.qwen_plus_client import QwenPlusClient, QwenPlusError
from me569_project.llm.sandbox import SandboxError, load_callable
from me569_project.sysid.llm_sysid_model import fit_with_basis_fn
from me569_project.sysid.polynomial_basis import make_polynomial_basis_fn


def run_condition(
    condition: str,
    basis_fn,
    train_data,
    val_data,
    feature_names=None,
    threshold: float = 0.1,
    extra: dict | None = None,
) -> dict:
    """Fit LLMBasisSysIDModel with the given basis and compute metrics."""
    print(f"[{condition}] Fitting with threshold={threshold} ...")
    t0 = time.time()
    model = fit_with_basis_fn(
        train_data,
        basis_fn=basis_fn,
        feature_names=feature_names,
        threshold=threshold,
    )
    fit_time = time.time() - t0
    print(f"[{condition}]   fit done in {fit_time:.1f}s, "
          f"n_basis={model.n_basis}, active_terms={model.active_terms}")

    print(f"[{condition}] Computing metrics ...")
    m1 = model.one_step_mse(val_data)
    m10 = model.rollout_mse(val_data, horizon=10)
    m50 = model.rollout_mse(val_data, horizon=50)
    print(f"[{condition}]   one_step_mse    = {m1:.6e}")
    print(f"[{condition}]   rollout_mse_10  = {m10:.6e}")
    print(f"[{condition}]   rollout_mse_50  = {m50:.6e}")

    row = {
        "condition": condition,
        "n_basis": model.n_basis,
        "active_terms": model.active_terms,
        "threshold": threshold,
        "one_step_mse": m1,
        "rollout_mse_10": m10,
        "rollout_mse_50": m50,
        "fit_time_s": fit_time,
    }
    if extra:
        row.update(extra)
    return row


def run_qwen_plus_condition(train_data, val_data, threshold: float = 0.1) -> dict | None:
    """Call Qwen-Plus, parse the basis, fit, and return the result row.

    Returns None if DASHSCOPE_API_KEY is not set or if the LLM response
    cannot be parsed into a runnable function.
    """
    api_key = os.environ.get("DASHSCOPE_API_KEY")
    if not api_key:
        print("[P] DASHSCOPE_API_KEY not set, skipping P condition.")
        return None

    client = QwenPlusClient(api_key=api_key, max_tokens=1500)
    prompt = build_sindy_basis_prompt()
    print(f"[P] Calling Qwen-Plus (prompt length: {len(prompt)} chars) ...")
    t0 = time.time()
    try:
        response = client.call(prompt)
    except QwenPlusError as e:
        print(f"[P] Qwen-Plus call failed: {e}")
        return None
    call_time = time.time() - t0
    print(f"[P]   response received in {call_time:.1f}s, "
          f"tokens={client.last_usage.get('total_tokens', '?') if client.last_usage else '?'}")

    try:
        code = extract_python_code(response)
    except CodeExtractionError as e:
        print(f"[P] Failed to extract code from response: {e}")
        print("Raw response:")
        print(response[:2000])
        return None

    print(f"[P]   extracted code ({len(code)} chars):")
    print("-" * 60)
    print(code)
    print("-" * 60)

    try:
        basis_fn = load_callable(code, function_name="basis")
    except SandboxError as e:
        print(f"[P] Sandbox failed to load basis function: {e}")
        return None

    # Verify it runs on a sample input before committing to a full fit
    import numpy as np
    try:
        sample_xu = np.array([0.1, 0.2, 0.05, 0.1, 0.0, 0.0, 4.9, 4.9])
        sample_out = basis_fn(sample_xu)
        n_basis_preview = len(list(sample_out))
        print(f"[P]   basis_fn preview: {n_basis_preview} features on sample input")
    except Exception as e:
        print(f"[P] basis_fn crashed on sample input: {e}")
        return None

    row = run_condition(
        condition="P",
        basis_fn=basis_fn,
        train_data=train_data,
        val_data=val_data,
        threshold=threshold,
        extra={
            "llm_call_time_s": call_time,
            "llm_model": "qwen-plus",
            "llm_total_tokens": (
                client.last_usage.get("total_tokens", 0)
                if client.last_usage
                else 0
            ),
            "llm_request_id": client.last_request_id or "",
        },
    )
    return row


def run_qwen_local_condition(train_data, val_data, threshold: float = 0.1) -> dict | None:
    """Call Qwen3.5-4B locally via mlx-vlm, parse the basis, fit, and return a row.

    Returns None on any LLM, parsing, or sandbox failure.
    """
    client = QwenLocalClient(max_tokens=2000)
    prompt = build_sindy_basis_prompt()
    print(f"[Q] Calling Qwen3.5-4B (prompt length: {len(prompt)} chars) ...")
    print("[Q]   (first call loads 4.8 GB model; subsequent calls reuse cache)")
    t0 = time.time()
    try:
        response = client.call(prompt)
    except QwenLocalError as e:
        print(f"[Q] Qwen3.5-4B call failed: {e}")
        return None
    call_time = time.time() - t0
    load_time = client.last_load_time_s or 0.0
    gen_time = client.last_call_time_s or 0.0
    print(f"[Q]   response received in {call_time:.1f}s "
          f"(load {load_time:.1f}s, generate {gen_time:.1f}s)")

    try:
        code = extract_python_code(response)
    except CodeExtractionError as e:
        print(f"[Q] Failed to extract code from response: {e}")
        print("Raw response (first 2000 chars):")
        print(response[:2000])
        return None

    print(f"[Q]   extracted code ({len(code)} chars):")
    print("-" * 60)
    print(code)
    print("-" * 60)

    try:
        basis_fn = load_callable(code, function_name="basis")
    except SandboxError as e:
        print(f"[Q] Sandbox failed to load basis function: {e}")
        return None

    import numpy as np
    try:
        sample_xu = np.array([0.1, 0.2, 0.05, 0.1, 0.0, 0.0, 4.9, 4.9])
        sample_out = basis_fn(sample_xu)
        n_basis_preview = len(list(sample_out))
        print(f"[Q]   basis_fn preview: {n_basis_preview} features on sample input")
    except Exception as e:
        print(f"[Q] basis_fn crashed on sample input: {e}")
        return None

    row = run_condition(
        condition="Q",
        basis_fn=basis_fn,
        train_data=train_data,
        val_data=val_data,
        threshold=threshold,
        extra={
            "llm_call_time_s": call_time,
            "llm_load_time_s": load_time,
            "llm_generate_time_s": gen_time,
            "llm_model": "Qwen3.5-4B-MLX-8bit",
        },
    )
    return row


def write_results_csv(rows: list[dict], path: Path) -> None:
    if not rows:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    # Union of all keys, preserving first-seen order
    keys: list[str] = []
    seen = set()
    for row in rows:
        for k in row.keys():
            if k not in seen:
                keys.append(k)
                seen.add(k)
    with path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=keys)
        writer.writeheader()
        for row in rows:
            writer.writerow({k: row.get(k, "") for k in keys})
    print(f"\nWrote {len(rows)} row(s) to {path}")


def main() -> None:
    num_train = 500
    num_val = 100
    steps_per_traj = 400
    threshold = 0.1

    print(f"Generating {num_train} train + {num_val} val trajectories at "
          f"{steps_per_traj} steps each ...")
    t0 = time.time()
    train = generate_trajectories(
        num_trajectories=num_train,
        steps_per_trajectory=steps_per_traj,
        seed=0,
    )
    val = generate_trajectories(
        num_trajectories=num_val,
        steps_per_trajectory=steps_per_traj,
        seed=42,
    )
    print(f"Data done in {time.time() - t0:.1f}s "
          f"({train.num_transitions} train transitions)")

    results = []

    # Baseline (B): polynomial library degree 3 via unified pipeline
    print()
    b_basis, b_names = make_polynomial_basis_fn(degree=3, n_input=8)
    b_row = run_condition(
        condition="B",
        basis_fn=b_basis,
        train_data=train,
        val_data=val,
        feature_names=b_names,
        threshold=threshold,
        extra={"basis_description": "polynomial degree 3"},
    )
    results.append(b_row)

    # Qwen-Plus (P)
    print()
    p_row = run_qwen_plus_condition(train, val, threshold=threshold)
    if p_row is not None:
        p_row["basis_description"] = "Qwen-Plus generated"
        results.append(p_row)

    # Qwen3.5-4B local (Q)
    if os.environ.get("E1_SKIP_Q"):
        print()
        print("[Q] E1_SKIP_Q is set, skipping Q condition.")
    else:
        print()
        q_row = run_qwen_local_condition(train, val, threshold=threshold)
        if q_row is not None:
            q_row["basis_description"] = "Qwen3.5-4B generated"
            results.append(q_row)

    print()
    print("=" * 72)
    print("E1 Results Summary")
    print("=" * 72)
    print(f"{'cond':4s} {'n_basis':>8s} {'active':>8s} "
          f"{'1step':>12s} {'roll10':>12s} {'roll50':>12s}")
    for r in results:
        print(
            f"{r['condition']:4s} {r['n_basis']:8d} {r['active_terms']:8d} "
            f"{r['one_step_mse']:12.4e} {r['rollout_mse_10']:12.4e} "
            f"{r['rollout_mse_50']:12.4e}"
        )
    print("=" * 72)

    write_results_csv(results, Path("results/e1_results.csv"))


if __name__ == "__main__":
    sys.exit(main())
